# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programer\Project\ARUP\ui\dlgSnippetsMgr.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgSnippetsMgr(object):
    def setupUi(self, dlgSnippetsMgr):
        dlgSnippetsMgr.setObjectName("dlgSnippetsMgr")
        dlgSnippetsMgr.resize(971, 591)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        dlgSnippetsMgr.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgSnippetsMgr.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgSnippetsMgr)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSave = QtWidgets.QPushButton(dlgSnippetsMgr)
        self.btnSave.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnSave.setFont(font)
        self.btnSave.setToolTip("")
        self.btnSave.setAutoDefault(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnUse = QtWidgets.QPushButton(dlgSnippetsMgr)
        self.btnUse.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnUse.setFont(font)
        self.btnUse.setToolTip("")
        self.btnUse.setAutoDefault(False)
        self.btnUse.setObjectName("btnUse")
        self.horizontalLayout.addWidget(self.btnUse)
        self.btnRename = QtWidgets.QPushButton(dlgSnippetsMgr)
        self.btnRename.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnRename.setFont(font)
        self.btnRename.setToolTip("")
        self.btnRename.setAutoDefault(False)
        self.btnRename.setObjectName("btnRename")
        self.horizontalLayout.addWidget(self.btnRename)
        self.btnDelete = QtWidgets.QPushButton(dlgSnippetsMgr)
        self.btnDelete.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnDelete.setFont(font)
        self.btnDelete.setToolTip("")
        self.btnDelete.setAutoDefault(False)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.btnClose = QtWidgets.QPushButton(dlgSnippetsMgr)
        self.btnClose.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnClose.setFont(font)
        self.btnClose.setToolTip("")
        self.btnClose.setAutoDefault(False)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.txtSearch = QtWidgets.QLineEdit(dlgSnippetsMgr)
        self.txtSearch.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtSearch.setFont(font)
        self.txtSearch.setClearButtonEnabled(True)
        self.txtSearch.setObjectName("txtSearch")
        self.horizontalLayout.addWidget(self.txtSearch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.spltListAndCode = QtWidgets.QSplitter(dlgSnippetsMgr)
        self.spltListAndCode.setOrientation(QtCore.Qt.Horizontal)
        self.spltListAndCode.setObjectName("spltListAndCode")
        self.treSnippets = QtWidgets.QTreeWidget(self.spltListAndCode)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.treSnippets.setFont(font)
        self.treSnippets.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treSnippets.setAlternatingRowColors(False)
        self.treSnippets.setRootIsDecorated(False)
        self.treSnippets.setItemsExpandable(False)
        self.treSnippets.setExpandsOnDoubleClick(False)
        self.treSnippets.setColumnCount(1)
        self.treSnippets.setObjectName("treSnippets")
        self.treSnippets.headerItem().setText(0, "1")
        self.treSnippets.header().setMinimumSectionSize(0)
        self.spltCodeAndDesc = QtWidgets.QSplitter(self.spltListAndCode)
        self.spltCodeAndDesc.setOrientation(QtCore.Qt.Vertical)
        self.spltCodeAndDesc.setObjectName("spltCodeAndDesc")
        self.txtCode = QtWidgets.QTextEdit(self.spltCodeAndDesc)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCode.setFont(font)
        self.txtCode.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtCode.setAcceptRichText(False)
        self.txtCode.setObjectName("txtCode")
        self.txtDesc = QtWidgets.QTextEdit(self.spltCodeAndDesc)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtDesc.setFont(font)
        self.txtDesc.setObjectName("txtDesc")
        self.verticalLayout.addWidget(self.spltListAndCode)

        self.retranslateUi(dlgSnippetsMgr)
        QtCore.QMetaObject.connectSlotsByName(dlgSnippetsMgr)
        dlgSnippetsMgr.setTabOrder(self.txtSearch, self.btnSave)
        dlgSnippetsMgr.setTabOrder(self.btnSave, self.btnUse)
        dlgSnippetsMgr.setTabOrder(self.btnUse, self.btnRename)
        dlgSnippetsMgr.setTabOrder(self.btnRename, self.btnDelete)
        dlgSnippetsMgr.setTabOrder(self.btnDelete, self.btnClose)
        dlgSnippetsMgr.setTabOrder(self.btnClose, self.treSnippets)
        dlgSnippetsMgr.setTabOrder(self.treSnippets, self.txtCode)
        dlgSnippetsMgr.setTabOrder(self.txtCode, self.txtDesc)

    def retranslateUi(self, dlgSnippetsMgr):
        _translate = QtCore.QCoreApplication.translate
        dlgSnippetsMgr.setWindowTitle(_translate("dlgSnippetsMgr", "Snippets Manager - ARUP"))
        self.btnSave.setText(_translate("dlgSnippetsMgr", "Save"))
        self.btnUse.setText(_translate("dlgSnippetsMgr", "Use"))
        self.btnRename.setText(_translate("dlgSnippetsMgr", "Rename"))
        self.btnDelete.setText(_translate("dlgSnippetsMgr", "Delete"))
        self.btnClose.setText(_translate("dlgSnippetsMgr", "Close"))
        self.txtSearch.setPlaceholderText(_translate("dlgSnippetsMgr", "Search"))
        self.txtCode.setPlaceholderText(_translate("dlgSnippetsMgr", "Code area"))
        self.txtDesc.setPlaceholderText(_translate("dlgSnippetsMgr", "Put description here"))


import res_rc
