# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programer\Project\ARUP\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgMain(object):
    def setupUi(self, dlgMain):
        dlgMain.setObjectName("dlgMain")
        dlgMain.resize(992, 591)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        dlgMain.setFont(font)
        dlgMain.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgMain.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(dlgMain)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtDirectory = QtWidgets.QLineEdit(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.txtDirectory.setFont(font)
        self.txtDirectory.setAcceptDrops(False)
        self.txtDirectory.setObjectName("txtDirectory")
        self.gridLayout.addWidget(self.txtDirectory, 0, 1, 1, 1)
        self.btnDirectory = QtWidgets.QPushButton(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnDirectory.setFont(font)
        self.btnDirectory.setAutoDefault(False)
        self.btnDirectory.setObjectName("btnDirectory")
        self.gridLayout.addWidget(self.btnDirectory, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.cmbFilter = QtWidgets.QComboBox(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cmbFilter.setFont(font)
        self.cmbFilter.setEditable(True)
        self.cmbFilter.setObjectName("cmbFilter")
        self.gridLayout.addWidget(self.cmbFilter, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.cmbSort = QtWidgets.QComboBox(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cmbSort.setFont(font)
        self.cmbSort.setObjectName("cmbSort")
        self.gridLayout.addWidget(self.cmbSort, 0, 6, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnMoveUp = QtWidgets.QPushButton(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnMoveUp.setFont(font)
        self.btnMoveUp.setToolTip("")
        self.btnMoveUp.setAutoDefault(False)
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.horizontalLayout.addWidget(self.btnMoveUp)
        self.btnMoveDown = QtWidgets.QPushButton(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnMoveDown.setFont(font)
        self.btnMoveDown.setToolTip("")
        self.btnMoveDown.setAutoDefault(False)
        self.btnMoveDown.setObjectName("btnMoveDown")
        self.horizontalLayout.addWidget(self.btnMoveDown)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnPreview = QtWidgets.QPushButton(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnPreview.setFont(font)
        self.btnPreview.setToolTip("")
        self.btnPreview.setAutoDefault(False)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout.addWidget(self.btnPreview)
        self.btnStart = QtWidgets.QPushButton(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnStart.setFont(font)
        self.btnStart.setAutoDefault(False)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnUndo = QtWidgets.QPushButton(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnUndo.setFont(font)
        self.btnUndo.setAutoDefault(False)
        self.btnUndo.setObjectName("btnUndo")
        self.horizontalLayout.addWidget(self.btnUndo)
        self.btnSnippet = QtWidgets.QPushButton(dlgMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnSnippet.setFont(font)
        self.btnSnippet.setAutoDefault(False)
        self.btnSnippet.setObjectName("btnSnippet")
        self.horizontalLayout.addWidget(self.btnSnippet)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 7)
        self.spltFileAndCode = QtWidgets.QSplitter(dlgMain)
        self.spltFileAndCode.setOrientation(QtCore.Qt.Horizontal)
        self.spltFileAndCode.setObjectName("spltFileAndCode")
        self.trePreview = QtWidgets.QTreeWidget(self.spltFileAndCode)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.trePreview.setFont(font)
        self.trePreview.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.trePreview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.trePreview.setAlternatingRowColors(True)
        self.trePreview.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.trePreview.setRootIsDecorated(False)
        self.trePreview.setItemsExpandable(False)
        self.trePreview.setExpandsOnDoubleClick(False)
        self.trePreview.setColumnCount(2)
        self.trePreview.setObjectName("trePreview")
        self.trePreview.headerItem().setText(0, "1")
        self.trePreview.headerItem().setText(1, "2")
        self.trePreview.header().setDefaultSectionSize(250)
        self.spltCodeAndOutput = QtWidgets.QSplitter(self.spltFileAndCode)
        self.spltCodeAndOutput.setOrientation(QtCore.Qt.Vertical)
        self.spltCodeAndOutput.setObjectName("spltCodeAndOutput")
        self.txtCode = QtWidgets.QTextEdit(self.spltCodeAndOutput)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.txtCode.setFont(font)
        self.txtCode.setAcceptDrops(False)
        self.txtCode.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtCode.setAcceptRichText(False)
        self.txtCode.setObjectName("txtCode")
        self.txtOutput = QtWidgets.QTextEdit(self.spltCodeAndOutput)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtOutput.setFont(font)
        self.txtOutput.setAcceptDrops(False)
        self.txtOutput.setAutoFillBackground(True)
        self.txtOutput.setStyleSheet("background-color: silver")
        self.txtOutput.setReadOnly(True)
        self.txtOutput.setObjectName("txtOutput")
        self.gridLayout.addWidget(self.spltFileAndCode, 2, 0, 1, 7)

        self.retranslateUi(dlgMain)
        QtCore.QMetaObject.connectSlotsByName(dlgMain)
        dlgMain.setTabOrder(self.txtDirectory, self.btnDirectory)
        dlgMain.setTabOrder(self.btnDirectory, self.cmbFilter)
        dlgMain.setTabOrder(self.cmbFilter, self.cmbSort)
        dlgMain.setTabOrder(self.cmbSort, self.btnMoveUp)
        dlgMain.setTabOrder(self.btnMoveUp, self.btnMoveDown)
        dlgMain.setTabOrder(self.btnMoveDown, self.btnPreview)
        dlgMain.setTabOrder(self.btnPreview, self.btnStart)
        dlgMain.setTabOrder(self.btnStart, self.btnUndo)
        dlgMain.setTabOrder(self.btnUndo, self.btnSnippet)
        dlgMain.setTabOrder(self.btnSnippet, self.trePreview)
        dlgMain.setTabOrder(self.trePreview, self.txtCode)
        dlgMain.setTabOrder(self.txtCode, self.txtOutput)

    def retranslateUi(self, dlgMain):
        _translate = QtCore.QCoreApplication.translate
        dlgMain.setWindowTitle(_translate("dlgMain", "ARUP - Another bulk Rename Utility with Python"))
        self.label.setText(_translate("dlgMain", "Directory:"))
        self.btnDirectory.setText(_translate("dlgMain", "..."))
        self.label_2.setText(_translate("dlgMain", "Filter:"))
        self.label_3.setText(_translate("dlgMain", "Sort:"))
        self.btnMoveUp.setText(_translate("dlgMain", "Up [F2]"))
        self.btnMoveDown.setText(_translate("dlgMain", "Down [F3]"))
        self.btnPreview.setText(_translate("dlgMain", "Preview [F5]"))
        self.btnStart.setText(_translate("dlgMain", "Start"))
        self.btnUndo.setText(_translate("dlgMain", "Undo"))
        self.btnSnippet.setText(_translate("dlgMain", "Snippets"))
        self.txtCode.setPlaceholderText(_translate("dlgMain", "Code area"))
        self.txtOutput.setPlaceholderText(_translate("dlgMain", "Output area"))


import res_rc
